### ISSUE TITLE
Refactor/improve chart

### ISSUE THREAD

**Issue by davidkarlsen** [anchore/anchore-charts#11]
Before solving other issues I'd like to refactor the chart to follow best practices. The `rbac.yaml` contains this rolebinding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: extension-{{ template "anchore-admission-controller.fullname" . }}-authentication-reader-default
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-api{{ template "anchore-admission-controller.fullname" . }}-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ template "anchore-admission-controller.fullname" . }}
```

which I find a bit strange as the role is not defined. 

Is it really for binding to the roles defined in  https://kubernetes.io/docs/tasks/access-kubernetes-api/ ?

I also see a cluster-rolebinding to a CR named `namespace-reservation-{{ template "anchore-admission-controller.fullname" . }}` - this does not exist, while `{{ template "anchore-admission-controller.fullname" . }}` does - is it a misspelling?
