### ISSUE TITLE
enabling/disabling feeds in values.yaml does not work unless booleans are quoted

### ISSUE THREAD

**Issue by Vijay-P** [anchore/anchore-charts#158]
enabling/disabling feeds in values.yaml does not work unless booleans are quoted

Broken Example:
```
anchoreEnterpriseFeeds:
  alpineDriverEnabled: false
  amazonDriverEnabled: false
  centosDriverEnabled: false
  debianDriverEnabled: false
  olDriverEnabled: false
  rhelDriverEnabled: false
  nvdDriverEnabled: false
  npmDriverEnabled: false
  gemDriverEnabled: false
  nvdv2DriverEnabled: false
  vulndbDriverEnabled: false
  msrcDriverEnabled: false
```

Working Example:
```
anchoreEnterpriseFeeds:
  alpineDriverEnabled: "false"
  amazonDriverEnabled: "false"
  centosDriverEnabled: "false"
  debianDriverEnabled: "false"
  olDriverEnabled: "false"
  rhelDriverEnabled: "false"
  nvdDriverEnabled: "false"
  npmDriverEnabled: "false"
  gemDriverEnabled: "false"
  nvdv2DriverEnabled: "false"
  vulndbDriverEnabled: "false"
  msrcDriverEnabled: "false"
```
