### ISSUE TITLE
Anchore Engine Chart - invalid default values

### ISSUE THREAD

**Issue by misterjacko** [anchore/anchore-charts#409]
In the v5.10.0 release a section was added to the default helm values that is invalid

```
anchoreConfig:
  policy_engine:
# vvv this part was added vvv
    vulnerabilities:
      matching:
        exclude:
          providers: null
          package_types: null
```

This conflicts with the requirements of the anchore_configmap template where those cant be null.

```
{{- $exclude_providers := required "anchoreConfig.policy_engine.vulnerabilities.matching.exclude.providers is required" .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.providers -}}
{{- $exclude_package := required "anchoreConfig.policy_engine.vulnerabilities.matching.exclude.package_types is required" .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.package_types -}}
```

The code expects a list there so the null values can be changed to empty lists `[]` and the base values will deploy. 

new values:

```
anchoreConfig:
  policy_engine:
    vulnerabilities:
      matching:
        exclude:
          providers: []
          package_types: []
```

will be submitting PR to resolve.
